## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
import numpy as np

In [3]:
#1
arr1 = np.zeros([10,10])
arr1[0,:].fill(1)
arr1[:,0].fill(1)
arr1[:,-1].fill(1)
arr1[-1,:].fill(1)
print(arr1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Create a 5*5 matrix with each row being 0 to 4

In [4]:
# 2
arr2 = np.array([[i for i in range(5)], [i for i in range(5)], [i for i in range(5)], [i for i in range(5)], [i for i in range(5)]])
print(arr2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [5]:
#3
arr3 = np.array([[0,1]*4,[1,0]*4])
for i in range(2):
    arr3 = np.row_stack((arr3,arr3))

print(arr3)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [6]:
#4
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr4[np.where(arr4%2 ==1)]
print(out)

[1 3 5 7 9]


5. Normalize a 5x5 random matrix 

In [15]:
# 5
arr5 = np.random.randint(0, 10, (5, 5))
min_max = (arr5 - np.min(arr5))/(np.max(arr5) - np.min(arr5))
Z_score = (arr5 - np.average(arr5)) / np.std(arr5)
print(arr5)
print(min_max)
print(Z_score) 

[[0 0 4 0 7]
 [5 4 6 5 1]
 [2 1 6 9 7]
 [0 1 4 9 3]
 [8 8 4 2 7]]
[[0.         0.         0.44444444 0.         0.77777778]
 [0.55555556 0.44444444 0.66666667 0.55555556 0.11111111]
 [0.22222222 0.11111111 0.66666667 1.         0.77777778]
 [0.         0.11111111 0.44444444 1.         0.33333333]
 [0.88888889 0.88888889 0.44444444 0.22222222 0.77777778]]
[[-1.39316454 -1.39316454 -0.04057761 -1.39316454  0.97386259]
 [ 0.29756912 -0.04057761  0.63571586  0.29756912 -1.0550178 ]
 [-0.71687107 -1.0550178   0.63571586  1.65015605  0.97386259]
 [-1.39316454 -1.0550178  -0.04057761  1.65015605 -0.37872434]
 [ 1.31200932  1.31200932 -0.04057761 -0.71687107  0.97386259]]


6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [8]:
#6
def get_radius(x, y):
    r = np.sqrt((x **2+y **2))
    return r

def get_angle(x, y):
    a = np.arctan2(y,x)
    return a

arr6 = np.random.randint(0,10,(10,2))
print(arr6)

[[1 6]
 [5 2]
 [9 5]
 [7 5]
 [0 4]
 [7 3]
 [4 3]
 [5 9]
 [0 6]
 [5 3]]


In [9]:
polar = []
for cor in arr6:
    polar.append([get_radius(cor[0],cor[1]), get_angle(cor[0], cor[1])])

polar = np.array(polar)
print(polar)

[[ 6.08276253  1.40564765]
 [ 5.38516481  0.38050638]
 [10.29563014  0.5070985 ]
 [ 8.60232527  0.62024949]
 [ 4.          1.57079633]
 [ 7.61577311  0.40489179]
 [ 5.          0.64350111]
 [10.29563014  1.06369782]
 [ 6.          1.57079633]
 [ 5.83095189  0.5404195 ]]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [10]:
# 7
arr7 = np.array([i+1 for i in range(4)])
print(arr7)
arr7 = arr7.reshape([4,1])
arr7 = np.insert(arr7, 1, [[0],[0],[0]], axis=1)
arr7 = arr7.flatten()
arr7 = np.append(arr7, 5)
print(arr7)

[1 2 3 4]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [11]:
#8
#nan是一个特殊的浮点数，其指数位为255，小数位不为0
#任何nan参与的运算结果都为nan
print(0 * np.nan)
#nan与任何数比较都为False
print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)
#这个是因为在比较两个相同的对象，所以结果是True
print(np.nan in set([np.nan]))

#因为浮点精度问题，3*0.1不等于0.3
print(0.3 == 3 * 0.1) 
print(3*0.1)

nan
False
False
nan
True
False
0.30000000000000004


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [12]:
#9
#在IEEE 754标准中，0/0结果为qnan，即0b0 11111111 10000000000000000000000
print(np.array(0) / np.array(0))
#python规定
print(np.array(0) // np.array(0))
#nan转换为int的类型转换没有被定义，这个值是int64的最小值
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/yd/5k827nkn5rbcnfly0n4b286c0000gn/T/ipykernel_21008/3945208201.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/yd/5k827nkn5rbcnfly0n4b286c0000gn/T/ipykernel_21008/3945208201.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [13]:
def repeat(word):
    return word + ', next ' + word + ', next ' + word + ', next ' + word

In [14]:
print(repeat('This'))

This, next This, next This, next This
